### ISSUE TITLE
this shouldn't be stored on GH

### ISSUE THREAD

**Issue by aric87** [danj707/foodme#5]
https://github.com/danj707/foodme/blob/master/index.js#L239

Lots of times, API keys are stored on GitHub for front end stuff because it ends up in the browser anyway. Here, you're password for an email account should definitely not be stored on GitHub. Change it to an environment variable, and change the password so that people aren't sending junk email from your account.

**Comment by danj707** [comment]
So this is an interesting one, and i'm not sure how to fix it.  The mailgun account I've setup is a 'test' account, that only allows emails to be sent TO verified domains.  Since I can't verify domains for the people who'll be signing up, I've set the TO email as my email.  Essentially, every time someone signs up, I get the email notification to myself.  It doesn't actually send an email, and the mailgun account can't be used for spam purposes, since it doesn't allow unverified domains to be mailed to.  So, I understand the fact I shouldn't be storing passwords for external accounts on GH, but in this case, it's not a security issue, and I'd like to keep the email testing to work.  In the future, if I was to expand this functionality, I would remove it as suggested above.
